# Generated by Django 5.0.6 on 2024-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_follower_post_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="followed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="liked_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="posted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
