# Generated by Django 5.0.6 on 2024-07-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_follower_followed_at_alter_like_liked_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="followed_at",
            new_name="timestamp",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="liked_at",
            new_name="timestamp",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="posted_at",
            new_name="timestamp",
        ),
    ]
