# Generated by Django 5.0.6 on 2024-07-09 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_rename_followed_at_follower_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="follower",
            name="is_archived",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="follower",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
