# Generated by Django 5.0.6 on 2024-07-11 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_follower_is_archived_alter_follower_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="is_archived",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_likes",
                to="network.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
