# Generated by Django 5.0.6 on 2024-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_like_is_archived_alter_like_post_alter_like_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="like",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
